### ISSUE TITLE
老哥，你这数据库的分数是怎么来的，有公开吗？

### ISSUE THREAD

**Issue by chibai** [avisingh599/face-rating#9]
我想用CNN做，借我finetune一下~~还有这些女星的颜值是怎么打分的？？？

**Comment by Morningxxx** [comment]
@chibai 兄弟，，这个项目是老外的，是个印度人，你发中文过分了呀。

**Comment by Morningxxx** [comment]
分数和图片来源来自于华南理工大学的一个实验室的公开数据。
